[build]
  command = "python3 manage.py collectstatic --noinput && python3 manage.py migrate"
  publish = "templates/static"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "coderstore.settings"
